apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: kubesense-backend-role

rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch