apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: joypatel2403/kubesense-backend
    newTag: "b7780ed"

  - name: joypatel2403/kubesense-frontend
    newTag: "b7780ed"