apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: joypatel2403/kubesense-backend
    newTag: 8c9ad08

  - name: joypatel2403/kubesense-frontend
    newTag: 8c9ad08